import "./globals.css";
import { CartProvider } from "./contexts/CartContext";
import ClientLayout from "./client";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <ClientLayout>{children}</ClientLayout> {/* Use the client component */}
        </CartProvider>
      </body>
    </html>
  );
}
